name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - release
      - hotfix
  pull_request:
    branches: ["master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'


      - name: Run Tests
        run: pnpm test

      - name: Build Production
        run: pnpm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/  # Vite 默认输出目录