name: CI/CD Pipeline

on:
  push:
    branches: [master, release, hotfix]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'


      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Type Check
        run: pnpm run typecheck  # 可选

      - name: Run Tests
        run: pnpm test

      - name: Build Production
        run: pnpm run build